complete -c j4-dmenu-desktop -f

complete -c j4-dmenu-desktop     -s b -l display-binary     -d "Display binary name after each entry"
complete -c j4-dmenu-desktop     -s f -l display-binary-base -d "Display basename of binary name after each entry"
complete -c j4-dmenu-desktop -Fr -s d -l dmenu              -d "Command used to invoke dmenu"
complete -c j4-dmenu-desktop          -l no-exec            -d "Do not execute selected command, send to stdout instead"
complete -c j4-dmenu-desktop          -l no-generic         -d "Do not include the generic name of desktop entries"
complete -c j4-dmenu-desktop -Fr -s t -l term               -d "Sets the terminal emulator used to start terminal apps"
complete -c j4-dmenu-desktop -Fr      -l usage-log          -d "Set usage log"
complete -c j4-dmenu-desktop          -l prune-bad-usage-log-entries -d "Remove bad history entries"
complete -c j4-dmenu-desktop     -s x -l use-xdg-de         -d "Enables reading \$XDG_CURRENT_DESKTOP to determine the desktop environment"
complete -c j4-dmenu-desktop -Fr      -l wait-on            -d "Enable daemon mode"
complete -c j4-dmenu-desktop -Fr      -l wrapper            -d "A wrapper binary"
complete -c j4-dmenu-desktop     -s I -l i3-ipc             -d "Execute desktop entries through i3 IPC"
complete -c j4-dmenu-desktop          -l skip-i3-exec-check -d "Disable the check for '--wrapper \"i3 exec\"'"
complete -c j4-dmenu-desktop     -s i -l case-insensitive   -d "Sort applications case insensitively"
complete -c j4-dmenu-desktop     -s v                       -d "Be more verbose, can be specified multiple times"
complete -c j4-dmenu-desktop -x       -l log-level -a "ERROR WARNING INFO DEBUG" -d "Set loglevel"
complete -c j4-dmenu-desktop -Fr      -l log-file           -d "Specify a log file"
complete -c j4-dmenu-desktop -x       -l log-file-level -a "ERROR WARNING INFO DEBUG" -d "Set file loglevel"
